"""load_secrets.py -- generate include/secrets.h from a gitignored .env file.

Reads secrets from .env in the project root and writes them out as C++
definitions: hex values (HEX_KEYS) become uint8_t[N] arrays of the declared
byte length, plain strings (STRING_KEYS) become #define macros. This keeps
credentials and per-deployment identifiers out of source control while still
baking them into the firmware at compile time.

Usage (standalone):
    python3 scripts/load_secrets.py

Usage (PlatformIO pre-build):
    extra_scripts = pre:scripts/load_secrets.py
"""

import os

# name -> byte length. Parsed as hex from .env, emitted as uint8_t[length].
HEX_KEYS = {
    "PMK_KEY": 16,
    "LMK_KEY": 16,
    "EVENT_BOARD_MAC": 6,
}
STRING_KEYS = ["SERVICE_UUID", "CHARACTERISTIC_UUID"]   # plain strings -> #define macros


def _parse_env(path: str) -> dict:
    values = {}
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _hex_to_c_array(name: str, hex_str: str, length: int) -> str:
    hex_str = hex_str.lower().replace(" ", "").replace(":", "").replace("-", "")
    expected_chars = length * 2
    if len(hex_str) != expected_chars:
        raise ValueError(
            f"{name} must be {expected_chars} hex characters ({length} bytes), "
            f"got {len(hex_str)}: {hex_str!r}"
        )
    try:
        raw = bytes.fromhex(hex_str)
    except ValueError as e:
        raise ValueError(f"{name} is not valid hex: {e}") from e
    bytes_c = ", ".join(f"0x{b:02X}" for b in raw)
    return f"static const uint8_t {name}[{length}] = {{{bytes_c}}};"


def _c_string_literal(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def run(project_dir: str) -> None:
    env_path = os.path.join(project_dir, ".env")
    out_path = os.path.join(project_dir, "include", "secrets.h")
    required = list(HEX_KEYS) + STRING_KEYS

    if not os.path.isfile(env_path):
        raise SystemExit(
            f"\n[load_secrets] Missing {env_path}\n"
            f"Copy .env.example to .env and fill in {', '.join(required)}.\n"
            f"See README.md ('Generating ESP-NOW keys') for how to generate them.\n"
        )

    values = _parse_env(env_path)
    missing = [k for k in required if k not in values or not values[k]]
    if missing:
        raise SystemExit(
            f"\n[load_secrets] .env is missing: {', '.join(missing)}\n"
            f"See README.md ('Generating ESP-NOW keys') for how to generate them.\n"
        )

    lines = [
        "// secrets.h -- GENERATED from .env by scripts/load_secrets.py.",
        "// Do not edit this file directly, and do not commit it.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
    ]
    for name, length in HEX_KEYS.items():
        lines.append(_hex_to_c_array(name, values[name], length))
    for key in STRING_KEYS:
        lines.append(f"#define {key} {_c_string_literal(values[key])}")
    lines.append("")

    content = "\n".join(lines)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    # Skip the write when nothing changed -- rewriting secrets.h every build
    # bumps its mtime and forces a full recompile of everything that includes it.
    try:
        with open(out_path, encoding="utf-8") as f:
            if f.read() == content:
                print("[load_secrets] include/secrets.h already up to date")
                return
    except FileNotFoundError:
        pass

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)

    print("[load_secrets] include/secrets.h regenerated from .env")


# PlatformIO extra_script entry point
try:
    Import("env")               # noqa: F821 -- injected by SCons
    run(env.subst("$PROJECT_DIR"))
except NameError:
    # Standalone
    _here = os.path.dirname(os.path.abspath(__file__))
    run(os.path.dirname(_here))
